### PR TITLE
Doc improvement

### PR DESCRIPTION
**Pull request by Magnitus-**
Clarification in documentation about requirements for the global Promise variable.

### CODE REVIEW

**Comment by dougwilson** [comment]
Thank you much!

**Comment by dougwilson** [comment]
Ok, I know I ended up changing the text on you (sorry!), but if you don't like the new text, please let me know and I can update it :)

**Comment by Magnitus-** [comment]
That's fine, this project is your show. Thanks for maintaining it.

I didn't know they supported promises in Node v 0.12, I was under the impression it didn't because it used an older version of V8 and only io.js supported them. Still using v 0.10 so I'd love to have confirmation on that one.

Also, any compelling reason to use bluebird compared to alternatives such as es6-promise or is it mostly a matter of personal taste?

**Comment by dougwilson** [comment]
Yes, they do exist on Node.js 0.12 :) I personally do not even use promises, and for everyone I know who does, uses `bluebird` and I usually see them using `bluebird` _instead_ of the built-in Promise since it's supposedly much, much faster. This was the only real reason I mentioned it (plus the prior major version of this module would use `bluebird`).

**Comment by Magnitus-** [comment]
Thanks a bunch for all the info. I'm still in the process of figuring out promises and whether or not I'll use them, but if I do, I guess I'll give bluebird a go.

**Comment by dougwilson** [comment]
Yea. I just haven't bitten the Promise bullet just yet :) But I know there are a lot of people who do want to use them.

**Pull request closed without merging**
